export const T = {
  // Colors
  navy: '#0F3460',
  navyDark: '#0A2444',
  navyLight: '#1A4A7A',
  teal: '#00D4AA',
  tealLight: '#E0FAF5',
  tealDark: '#00A886',
  bg: '#F0F4FF',
  surface: '#FFFFFF',
  border: '#E0E6F0',
  borderDark: '#C8D4E8',
  ink: '#1A1A2E',
  inkMid: '#4A5068',
  inkMuted: '#8892A4',
  green: '#2ECC71',
  greenLight: '#E8F8F0',
  greenDark: '#0F7040',
  coral: '#FF6B6B',
  coralLight: '#FFF0F0',
  amber: '#FFB347',
  amberLight: '#FFF8E0',
  amberDark: '#9A6500',
  shadow: '0 1px 3px rgba(15,52,96,0.08), 0 4px 12px rgba(15,52,96,0.05)',
  shadowMd: '0 2px 8px rgba(15,52,96,0.10), 0 8px 24px rgba(15,52,96,0.07)',
  radius: 14,
  radiusSm: 10,
  radiusLg: 18,
};

export const input = {
  width: '100%',
  background: T.bg,
  border: `1px solid ${T.border}`,
  borderRadius: T.radiusSm,
  padding: '9px 12px',
  fontSize: 13,
  outline: 'none',
  boxSizing: 'border-box' as const,
  fontFamily: 'inherit',
  color: T.ink,
};

export const label = {
  fontSize: 11,
  color: T.inkMuted,
  fontWeight: 700,
  textTransform: 'uppercase' as const,
  letterSpacing: '0.4px',
  display: 'block',
  marginBottom: 5,
};

export const card = {
  background: T.surface,
  border: `1px solid ${T.border}`,
  borderRadius: T.radius,
  padding: 22,
  boxShadow: T.shadow,
};

export const btn = {
  primary: {
    background: T.navy,
    color: '#fff',
    border: 'none',
    borderRadius: T.radiusSm,
    padding: '9px 20px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  ghost: {
    background: 'transparent',
    color: T.inkMuted,
    border: `1px solid ${T.border}`,
    borderRadius: T.radiusSm,
    padding: '9px 20px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  teal: {
    background: T.tealLight,
    color: T.tealDark,
    border: `1px solid ${T.teal}33`,
    borderRadius: T.radiusSm,
    padding: '9px 20px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  danger: {
    background: T.coralLight,
    color: T.coral,
    border: 'none',
    borderRadius: T.radiusSm,
    padding: '9px 20px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
};