// lib/compliance/disclaimer-texts.ts
//
// Plain data module (no 'use client', no React) so server-only code — like
// PDF generation in Route Handlers — can import these strings directly.
// Client components should still get them via LegalDisclaimer.tsx's re-export;
// importing a 'use client' module from a Route Handler resolves to a stripped
// client-reference proxy, not the real string values.

export const DISCLAIMER_VERSION = 1;

export const DISCLAIMER_TEXTS = {
  acknowledgment:
    'By using this tool, I acknowledge that the outputs are informational only and not legal advice. Keywise is not a law firm. I will consult a licensed California attorney before making decisions that have legal or financial consequences. Keywise is not liable for any losses, damages, or legal outcomes resulting from my use of or reliance on this tool.',
  prominent:
    'This is informational only — not legal advice. California rental law is complex and changes frequently. Verify with a licensed California attorney before relying on these results. Keywise is not responsible for legal outcomes from use of this tool.',
  inline:
    'Informational only. Not legal advice.',
  document_footer:
    'This document was generated by Keywise.app as an informational aid based on user-provided inputs. Keywise is not a law firm and does not provide legal advice. Before serving, filing, or relying on this document, verify all content with a licensed California attorney. Keywise expressly disclaims liability for any legal outcomes, damages, or losses arising from use of this document.',
};
