import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { email, address, currentRent, newRent, increasePercent, effectiveDate, noticeDate, region, inputs } = body;

    // Validate email
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
    }

    // Save lead to Supabase (non-blocking — don't fail request if table missing)
    try {
      const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!
      );

      await supabase.from('leads').insert({
        email,
        source: 'ab1482_calculator',
        metadata: { address, currentRent, newRent, increasePercent, region, ...inputs },
      });
    } catch (dbErr) {
      console.warn('[ab1482-notice] Lead save failed (non-fatal):', dbErr);
    }

    // Generate notice text
    const propertyAddress = address || '[Property Address]';
    const noticePeriod = (increasePercent ?? 0) >= 10 ? '90' : '30';

    const currentRentFormatted = typeof currentRent === 'number'
      ? currentRent.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
      : String(currentRent ?? '[Current Rent]');

    const newRentFormatted = typeof newRent === 'number'
      ? newRent.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
      : String(newRent ?? '[New Rent]');

    const noticeDateStr = noticeDate || new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    const effectiveDateStr = effectiveDate || '[Effective Date]';

    const noticeText = `NOTICE OF CHANGE IN TERMS OF TENANCY — RENT INCREASE

Property Address: ${propertyAddress}

To the Tenant(s) in possession:

You are hereby notified that effective ${effectiveDateStr} (at least ${noticePeriod} days from the date this notice is served), the monthly rent for the above-referenced premises will be changed as follows:

  Current monthly rent:  $${currentRentFormatted}
  New monthly rent:      $${newRentFormatted}
  Increase amount:       ${increasePercent}% (within AB 1482 allowable maximum)

This rent increase is provided pursuant to California Civil Code Section 827 and the Tenant Protection Act of 2019 (AB 1482).

All other terms of your tenancy remain the same.

Date of Notice: ${noticeDateStr}

Landlord/Agent Signature: ___________________________

Landlord/Agent Name (print): ___________________________

Address for Landlord/Agent: ___________________________


---
PROOF OF SERVICE

I, the undersigned, declare that on __________, I served this notice on the above-named tenant(s) by:

[ ] Personal delivery to the tenant(s)
[ ] First-class mail (adds 5 days to notice period under CCP 1013)
[ ] Other: ___________________________

Served by: ___________________________  Date: ___________________________


Generated by Keywise — keywise.app
California Landlord Compliance, Done Right.`;

    // Send via Resend
    const resend = new Resend(process.env.RESEND_API_KEY);

    await resend.emails.send({
      from: 'Keywise <hello@keywise.app>',
      to: email,
      subject: 'Your AB 1482 Rent Increase Notice',
      text: `Hey — here's your notice, ready to serve.

The rent increase notice is attached below. It's formatted to meet California Civil Code Section 827 requirements for AB 1482 rent increases.

A few things to double-check before serving:
- Confirm the effective date is at least ${noticePeriod} days from the notice date
- Serve via personal delivery, or first-class mail (which adds 5 days to the notice period under CCP 1013)
- Keep a copy for your records

Managing more than one property? Keywise tracks all your California compliance in one place — AB 1482, just-cause evictions, security deposits, move-out inspections. Free for 1-2 units.

→ https://keywise.app

— Chris (Keywise)

---

${noticeText}`,
      attachments: [
        {
          filename: 'rent-increase-notice.txt',
          content: Buffer.from(noticeText).toString('base64'),
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Internal server error';
    console.error('[ab1482-notice] Error:', err);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
