'use client';

import { useState, useEffect } from 'react';

const DISCLAIMER_VERSION = 1;

const TEXTS = {
  acknowledgment:
    'By using this tool, I acknowledge that the outputs are informational only and not legal advice. Keywise is not a law firm. I will consult a licensed California attorney before making decisions that have legal or financial consequences. Keywise is not liable for any losses, damages, or legal outcomes resulting from my use of or reliance on this tool.',
  prominent:
    'This is informational only — not legal advice. California rental law is complex and changes frequently. Verify with a licensed California attorney before relying on these results. Keywise is not responsible for legal outcomes from use of this tool.',
  inline:
    'Informational only. Not legal advice.',
  document_footer:
    'This document was generated by Keywise.app as an informational aid based on user-provided inputs. Keywise is not a law firm and does not provide legal advice. Before serving, filing, or relying on this document, verify all content with a licensed California attorney. Keywise expressly disclaims liability for any legal outcomes, damages, or losses arising from use of this document.',
};

export { TEXTS as DISCLAIMER_TEXTS, DISCLAIMER_VERSION };

const N = '#0F3460';
const CORAL = '#FF6B6B';
const CORAL_LIGHT = '#FFEDED';
const BORDER = '#E0E6F0';
const INK_MUTED = '#8892A4';
const BG = '#F0F4FF';

interface LegalDisclaimerProps {
  variant: 'acknowledgment' | 'prominent' | 'inline' | 'document_footer';
  toolId?: string;
  onAcknowledge?: () => void;
}

function getStorageKey(toolId: string) {
  return `kw_disclaimer_${toolId}_v${DISCLAIMER_VERSION}`;
}

export function isDisclaimerAcknowledged(toolId: string): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(getStorageKey(toolId)) === 'true';
}

export default function LegalDisclaimer({ variant, toolId, onAcknowledge }: LegalDisclaimerProps) {
  const [checked, setChecked] = useState(false);
  const [acknowledged, setAcknowledged] = useState(true); // default true to avoid flash

  useEffect(() => {
    if (variant === 'acknowledgment' && toolId) {
      setAcknowledged(isDisclaimerAcknowledged(toolId));
    }
  }, [variant, toolId]);

  if (variant === 'acknowledgment') {
    if (acknowledged) return null;
    return (
      <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,52,96,0.7)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
        <div style={{ background: '#fff', borderRadius: 16, padding: 28, maxWidth: 480, width: '100%', boxShadow: '0 8px 40px rgba(15,52,96,0.25)' }}>
          <div style={{ fontSize: 18, fontWeight: 800, color: N, marginBottom: 4 }}>Before you begin</div>
          <div style={{ fontSize: 13, color: INK_MUTED, marginBottom: 16 }}>Please read and acknowledge the following:</div>
          <div style={{ background: BG, border: `1px solid ${BORDER}`, borderRadius: 10, padding: 16, fontSize: 13, color: '#333', lineHeight: 1.7, marginBottom: 20 }}>
            {TEXTS.acknowledgment}
          </div>
          <label style={{ display: 'flex', alignItems: 'flex-start', gap: 10, cursor: 'pointer', fontSize: 13, color: N, marginBottom: 16 }}>
            <input
              type="checkbox"
              checked={checked}
              onChange={e => setChecked(e.target.checked)}
              style={{ marginTop: 2, width: 18, height: 18, flexShrink: 0 }}
            />
            <span>I have read and understand this disclaimer</span>
          </label>
          <button
            disabled={!checked}
            onClick={() => {
              if (toolId) localStorage.setItem(getStorageKey(toolId), 'true');
              setAcknowledged(true);
              onAcknowledge?.();
            }}
            style={{
              width: '100%', background: checked ? N : '#C8CDD8', color: '#fff',
              border: 'none', borderRadius: 10, padding: '13px', fontSize: 15,
              fontWeight: 700, cursor: checked ? 'pointer' : 'default', fontFamily: 'inherit',
            }}
          >
            I understand — continue
          </button>
        </div>
      </div>
    );
  }

  if (variant === 'prominent') {
    return (
      <div style={{ background: CORAL_LIGHT, border: `1px solid ${CORAL}33`, borderRadius: 10, padding: '12px 16px', marginBottom: 16 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: CORAL, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 4 }}>Legal Disclaimer</div>
        <div style={{ fontSize: 12, color: '#4A5068', lineHeight: 1.6 }}>{TEXTS.prominent}</div>
      </div>
    );
  }

  if (variant === 'inline') {
    return (
      <span style={{ fontSize: 11, color: INK_MUTED }}>
        {TEXTS.inline}{' '}
        <a href="/legal/disclaimer" style={{ color: INK_MUTED, textDecoration: 'underline' }}>See full disclaimer.</a>
      </span>
    );
  }

  if (variant === 'document_footer') {
    return (
      <div style={{ borderTop: `1px solid ${BORDER}`, marginTop: 24, paddingTop: 12, fontSize: 10, color: INK_MUTED, lineHeight: 1.6 }}>
        {TEXTS.document_footer}
      </div>
    );
  }

  return null;
}
