import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Legal Disclaimer | Keywise',
  description: 'Keywise compliance tools provide informational estimates only — not legal advice. Read our full legal disclaimer.',
  robots: { index: true, follow: true },
};

const N = '#0F3460';
const TEAL = '#00D4AA';
const BORDER = '#E0E6F0';
const INK = '#1A1A2E';
const INK_MID = '#4A5068';
const INK_MUTED = '#8892A4';

export default function DisclaimerPage() {
  return (
    <div style={{ fontFamily: "'Inter', system-ui, sans-serif", background: '#fff', color: INK, minHeight: '100vh' }}>
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />

      <nav style={{ borderBottom: `1px solid ${BORDER}`, padding: '0 40px', height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link href="/" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 28, height: 28, borderRadius: 7, background: N, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <svg width="16" height="16" viewBox="0 0 32 32" fill="none">
              <circle cx="13" cy="16" r="5.5" fill="none" stroke={TEAL} strokeWidth="2.5" />
              <circle cx="13" cy="16" r="2" fill={TEAL} />
              <rect x="17.5" y="14.75" width="8" height="2.5" rx="1.25" fill={TEAL} />
            </svg>
          </div>
          <span style={{ fontSize: 16, fontWeight: 700, color: N, letterSpacing: '-0.3px' }}>keywise</span>
        </Link>
        <Link href="/" style={{ fontSize: 13, color: INK_MID, textDecoration: 'none', fontWeight: 500 }}>← Home</Link>
      </nav>

      <article style={{ maxWidth: 680, margin: '0 auto', padding: '60px 24px', lineHeight: 1.8 }}>
        <div style={{ fontSize: 12, color: INK_MUTED, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 12 }}>Legal · Last updated June 2026</div>
        <h1 style={{ fontSize: 32, fontWeight: 800, color: N, letterSpacing: '-0.8px', marginBottom: 24, lineHeight: 1.2 }}>
          Legal Disclaimer
        </h1>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>General Disclaimer</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          Keywise provides software tools that generate informational estimates and documents based on user-provided inputs and publicly available legal data. <strong>Keywise is not a law firm and does not provide legal advice.</strong> The use of Keywise tools does not create an attorney-client relationship.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>Compliance Tools</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          The AB 1482 Rent Cap Calculator, AB 2801 Move-Out Documentation Workflow, and Just-Cause Eviction Notice Wizard provide informational estimates and document templates based on California statutory requirements. These tools are designed to assist landlords in understanding their obligations — they are not a substitute for professional legal counsel.
        </p>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          California rental law is complex, varies by locality, and changes frequently. The outputs of these tools depend on the accuracy of user-provided inputs and the currency of the legal data programmed into the system. Keywise makes reasonable efforts to keep legal data current but does not guarantee accuracy, completeness, or timeliness.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>Limitation of Liability</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          Keywise expressly disclaims liability for any losses, damages, penalties, fines, legal fees, or adverse legal outcomes arising from use of or reliance on any Keywise tool, document, estimate, or output. Users assume full responsibility for verifying all outputs with a licensed California attorney before taking action.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>Generated Documents</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          Documents generated by Keywise (including eviction notices, deposit itemizations, and inspection reports) are informational aids based on user-provided inputs. Before serving, filing, or relying on any generated document, verify all content with a licensed California attorney. An improperly drafted or served legal document can result in case dismissal, financial penalties, and other adverse outcomes.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>AI-Generated Content</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          Some Keywise features use artificial intelligence to analyze photographs, compare property conditions, or suggest deduction amounts. AI observations are suggestions only and do not constitute legal judgments about liability, fault, or permissible deductions. Users must independently verify all AI-generated findings.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: N, marginTop: 32, marginBottom: 12 }}>Seek Legal Counsel</h2>
        <p style={{ fontSize: 15, color: INK_MID, marginBottom: 16 }}>
          For legal advice specific to your situation, consult a licensed California attorney. The California State Bar offers a Lawyer Referral Service at{' '}
          <a href="https://www.calbar.ca.gov/Public/Need-Legal-Help/Lawyer-Referral-Service" style={{ color: TEAL, fontWeight: 600 }} target="_blank" rel="noopener noreferrer">
            calbar.ca.gov
          </a>.
        </p>

        <div style={{ borderTop: `1px solid ${BORDER}`, marginTop: 40, paddingTop: 20, fontSize: 13, color: INK_MUTED }}>
          <p style={{ margin: 0 }}>Keywise, Inc. · <a href="https://keywise.app" style={{ color: INK_MUTED }}>keywise.app</a></p>
        </div>
      </article>
    </div>
  );
}
